Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Layout/LineLength:
  Max: 120


